apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: kub4y6ntr-go 
  janus-idp.io/tekton: kub4y6ntr-go
  backstage.io/kubernetes-id: kub4y6ntr-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: kub4y6ntr-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  