apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: kub4y6ntr-go
  janus-idp.io/tekton: kub4y6ntr-go
  backstage.io/kubernetes-id: kub4y6ntr-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: kub4y6ntr-go
resources:
- deployment.yaml
- route.yaml
- service.yaml
