apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: kub4y6ntr-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: kub4y6ntr-go 
  name: kub4y6ntr-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: kub4y6ntr-go 
